"""Generate low-fidelity BN/Al2O3 data from DF-selected candidates.

This is a thin CLI wrapper around :mod:`phygnn.bn_al2o3.data`. It reads the
particle-size candidates from :mod:`select_df_particle_sizes`, optionally
merges measured low-cost packing data, then calculates low-fidelity thermal
conductivity with the Lewis-Nielsen model.

The current PGNN feature set uses:
    D_s,D_m,D_l,phi_s,phi_m,E
"""

from __future__ import annotations

import argparse
from pathlib import Path

from phygnn.bn_al2o3.data import (
    demo_powder_table,
    generate_lf_data,
    load_df_candidates,
    merge_packing_data,
    save_training_tables,
    select_df_triplets,
)
from phygnn.bn_al2o3.paths import data_path


def build_parser():
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        description='Generate LF BN/Al2O3 data from DF particle candidates.'
    )
    parser.add_argument(
        '--df-candidates',
        type=Path,
        default=data_path('df_particle_candidates.csv'),
        help='CSV generated by select_df_particle_sizes.py.',
    )
    parser.add_argument(
        '--powders',
        type=Path,
        default=None,
        help='Original powder CSV; required for ratio perturbation.',
    )
    parser.add_argument(
        '--packing-data',
        type=Path,
        default=None,
        help='Optional CSV with triplet_id and measured phi_max.',
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=data_path('lf_bn_al2o3_data.csv'),
        help='Combined LF output CSV path.',
    )
    parser.add_argument(
        '--features-output',
        type=Path,
        default=None,
        help='Optional PGNN feature CSV path.',
    )
    parser.add_argument(
        '--labels-output',
        type=Path,
        default=None,
        help='Optional PGNN label CSV path.',
    )
    parser.add_argument(
        '--demo',
        action='store_true',
        help='Generate demo DF candidates when real inputs are unavailable.',
    )
    parser.add_argument(
        '--n-samples',
        type=int,
        default=0,
        help='Rows to generate. Use <=0 to use every candidate once.',
    )
    parser.add_argument(
        '--top-n-candidates',
        type=int,
        default=0,
        help='Use only the best N DF candidate rows. Use <=0 for all.',
    )
    parser.add_argument(
        '--ratio-concentration',
        type=float,
        default=0.0,
        help='Dirichlet concentration for ratio perturbation. 0 disables it.',
    )
    parser.add_argument(
        '--seed',
        type=int,
        default=42,
        help='Random seed for sampling and optional LF noise.',
    )
    parser.add_argument('--vf', type=float, default=0.30)
    parser.add_argument('--vf-min', type=float, default=None)
    parser.add_argument('--vf-max', type=float, default=None)
    parser.add_argument('--k0', type=float, default=1.50)
    parser.add_argument('--k-al2o3', type=float, default=30.0)
    parser.add_argument('--shape-factor', type=float, default=1.5)
    parser.add_argument('--phi-max-fixed', type=float, default=None)
    parser.add_argument('--phi-max-upper', type=float, default=0.68)
    parser.add_argument('--phi-max-lower', type=float, default=0.50)
    parser.add_argument('--phi-max-error-scale', type=float, default=1.5)
    parser.add_argument('--df-exponent', type=float, default=0.37)
    parser.add_argument('--grid-points', type=int, default=240)
    parser.add_argument('--noise-frac', type=float, default=0.0)
    return parser


def main(argv=None):
    """Run the LF data-generation CLI."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.demo:
        powders = demo_powder_table()
        candidates = select_df_triplets(
            powders,
            top_n=max(args.n_samples, 30),
            keep_all_ratios=True,
        )
        args.powders = None
        print('Using embedded demo DF candidates.')
    else:
        if not args.df_candidates.exists():
            msg = (
                'DF candidate CSV not found: {}. Run '
                'select_df_particle_sizes.py first or use --demo.'
            ).format(args.df_candidates)
            raise FileNotFoundError(msg)
        candidates = load_df_candidates(args.df_candidates)
        powders = args.powders

    candidates = merge_packing_data(candidates, args.packing_data)
    lf_data = generate_lf_data(
        candidates,
        n_samples=args.n_samples,
        seed=args.seed,
        top_n_candidates=args.top_n_candidates,
        ratio_concentration=args.ratio_concentration,
        powders=powders,
        df_exponent=args.df_exponent,
        grid_points=args.grid_points,
        vf=args.vf,
        vf_min=args.vf_min,
        vf_max=args.vf_max,
        k0=args.k0,
        k_al2o3=args.k_al2o3,
        shape_factor=args.shape_factor,
        phi_max_fixed=args.phi_max_fixed,
        phi_max_upper=args.phi_max_upper,
        phi_max_lower=args.phi_max_lower,
        phi_max_error_scale=args.phi_max_error_scale,
        noise_frac=args.noise_frac,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    lf_data.to_csv(args.output, index=False, encoding='utf-8-sig')
    save_training_tables(
        lf_data,
        features_output=args.features_output,
        labels_output=args.labels_output,
    )

    preview_cols = [
        'sample_id',
        'triplet_id',
        'D_s',
        'D_m',
        'D_l',
        'phi_s',
        'phi_m',
        'E',
        'phi_max',
        'V_f',
        'k_LF',
    ]
    print('Saved {} LF rows to {}'.format(len(lf_data),
                                          args.output.resolve()))
    print(lf_data[preview_cols].head(10).to_string(index=False))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
